all:
	g++ --std=c++11 -o a.out q-pool.cpp -Wall -lm -lboost_system -Wall -lm -lgs -lgslcblas -I/home/z/.morloc/lib/cppbase -I/home/z/.morloc/lib/math -I/home/z/.morloc/lib/optimization


clean:
	rm -f pool* nexus* a.out
