#!/bin/sh
exec mim "$0" "$@"
### MANIFEST ###
{"version":1,"build_time":1771049184,"pools":[{"lang":"python3","exec":["python3","/home/z/.local/share/morloc/exe/foo-a9bf4853510e3349/pool.py"],"socket":"pipe-python3"}],"commands":[{"name":"test","type":"remote","mid":1,"pool":0,"needed_pools":[0],"arg_schemas":[],"return_schema":"<bool>b","desc":[],"return_type":"Bool","return_desc":[],"args":[]}]}