#!/usr/bin/env bash
cat <<EOF > exp
hi from sh
hi from py
hi from R
EOF
stat=0
loc -kx locout x.loc || stat=1
./manifold-nexus.py main
diff exp obs || stat=1

rm -rf locout exp obs manifold-nexus.py
exit $stat
