name:             morloc
version:          0.47.1
homepage:         https://github.com/morloc-project/morloc
synopsis:         A multi-lingual, typed, workflow language
description:      See GitHub README <https://github.com/morloc-project/morloc#readme>
category:         Language, Compiler, Code Generation
license:          GPL-3
license-file:     LICENSE
author:           "Zebulun Arendsee" 
maintainer:       "zbwrbz@gmail.com"
github:           "morloc-project/morloc"
bug-reports:      https://github.com/morloc-project/morloc/issues
copyright:        "2020 Zebulun Arendsee"

extra-source-files:
  - README.md
  - ChangeLog.md

default-extensions:
  - TypeOperators

dependencies:
  - base
  - aeson
  - bytestring
  - containers
  - directory
  - directory-tree
  - extra
  - filepath
  - haskell-src-meta
  - megaparsec
  - mtl
  - parsec
  - partial-order
  - pretty-simple
  - prettyprinter
  - process
  - raw-strings-qq
  - safe
  - scientific
  - template-haskell
  - text
  - unordered-containers
  - yaml


ghc-options:
  - -Wall
  - -Wcompat
  - -fwarn-unused-binds
  - -fwarn-unused-imports 
  - -fwarn-tabs
  - -fwarn-incomplete-uni-patterns
  - -fwarn-incomplete-record-updates
  - -fwarn-redundant-constraints
  - -fno-warn-missing-signatures
  - -fno-warn-unused-do-bind
  - -fno-warn-orphans
  - -haddock

library:
  source-dirs: library

executables:
  morloc:
    main:          Main.hs
    source-dirs:   executable
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
      # The static build requires a static `libgmp.a` file
      # On arch, this requires libgmp-static from AUR
      # On debian systems, libgmp-dev should cover it
      - -static
      - -haddock
    cc-options:
      - -static
    ld-options:
      - -static
    dependencies:
      - morloc 
      - base
      - optparse-applicative
      - text

tests:
  morloc-test:
    main:          Main.hs
    source-dirs:   test-suite
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - morloc
      - base
      - QuickCheck
      - tasty
      - tasty-golden
      - tasty-hunit
      - tasty-quickcheck
