name:             morloc
version:          0.60.0
homepage:         https://github.com/morloc-project/morloc
synopsis:         A multi-lingual, typed, workflow language
description: |
  Morloc is a typed, multi-lingual workflow language that composes functions
  across Python, C++, R, and other languages under a unified type system.
  The compiler generates interprocess communication code, serialization
  logic, and a dispatch binary from a single morloc source file.
  See the GitHub README <https://github.com/morloc-project/morloc#readme>
  for full documentation.
category:         Language, Compiler, Code Generation
tested-with:      GHC == 9.6.6
license:          Apache-2.0
license-file:     LICENSE
author:           "Zebulun Arendsee" 
maintainer:       "z@morloc.io"
github:           "morloc-project/morloc"
bug-reports:      https://github.com/morloc-project/morloc/issues
copyright:        "2026 Zebulun Arendsee"

extra-source-files:
  - README.md
  - ChangeLog.md
  # libraries
  - data/nexus.c # nexus template
  - data/lang/cpp/pool.cpp
  # universal c library (split into modules)
  - data/morloc/morloc.h
  - data/morloc/macros.h
  - data/morloc/memory.h
  - data/morloc/call.h
  - data/morloc/packet.h
  - data/morloc/schema.h
  - data/morloc/eval.h
  - data/morloc/slurm.h
  - data/morloc/utility.h
  - data/morloc/mpack.h
  - data/morloc/json.h
  - data/morloc/cache.h
  - data/morloc/xxhash.h
  - data/morloc/cache.c
  - data/morloc/cli.c
  - data/morloc/eval.c
  - data/morloc/ipc.c
  - data/morloc/json.c
  - data/morloc/mpack.c
  - data/morloc/packet.c
  - data/morloc/schema.c
  - data/morloc/serialize.c
  - data/morloc/shm.c
  - data/morloc/slurm.c
  - data/morloc/utility.c
  # shared language config
  - data/lang/languages.yaml
  # per-language files
  - data/lang/c/lang.yaml
  - data/lang/cpp/lang.yaml
  - data/lang/cpp/cppmorloc.hpp
  - data/lang/cpp/cppmorloc.cpp
  - data/lang/cpp/morloc_pch.hpp
  - data/lang/cpp/pool.cpp
  - data/lang/cpp/init.sh
  - data/lang/py/lang.yaml
  - data/lang/py/pymorloc.c
  - data/lang/py/setup.py
  - data/lang/py/Makefile
  - data/lang/py/pool.py
  - data/lang/py/init.sh
  - data/lang/r/lang.yaml
  - data/lang/r/rmorloc.c
  - data/lang/r/pool.R
  - data/lang/r/init.sh
  - data/lang/julia/juliabridge.c
  - data/lang/julia/MorlocRuntime.jl
  - data/lang/julia/lang.yaml
  - data/lang/julia/pool.jl
  - data/lang/julia/init.sh

default-extensions:
  - TypeOperators

dependencies:
  - base
  - aeson
  - binary
  - array
  - bytestring
  - containers
  - directory
  - directory-tree
  - extra
  - filepath
  - file-embed
  - haskell-src-meta
  - http-conduit
  - http-types
  - megaparsec
  - mtl
  - parsec
  - partial-order
  - pretty-simple
  - prettyprinter
  - process
  - raw-strings-qq
  - safe
  - scientific
  - template-haskell
  - text
  - time
  - unordered-containers
  - yaml
  - zip-archive

ghc-options:
  - -Wall
  - -Wcompat
  - -fwarn-unused-binds
  - -fwarn-unused-imports 
  - -fwarn-tabs
  - -fwarn-incomplete-uni-patterns
  - -fwarn-incomplete-record-updates
  - -fwarn-redundant-constraints
  - -fno-warn-missing-signatures
  - -fno-warn-unused-do-bind
  - -fno-warn-orphans
  - -haddock

library:
  source-dirs: library
  build-tools:
    - happy

executables:
  morloc:
    main:          Main.hs
    source-dirs:   executable
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
      - -haddock
    dependencies:
      - morloc
      - base
      - optparse-applicative
      - text

  morloc-codegen-generic:
    main:          Main.hs
    source-dirs:   exe/morloc-codegen-generic
    ghc-options:
      - -Wall
      - -O2
    dependencies:
      - morloc
      - base
      - aeson
      - binary
      - bytestring
      - text
      - yaml

tests:
  morloc-test:
    main:          Main.hs
    source-dirs:   test-suite
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - morloc
      - base
      - QuickCheck
      - tasty
      - tasty-golden
      - tasty-hunit
      - tasty-quickcheck

benchmarks:
  morloc-bench:
    main:          Bench.hs
    source-dirs:   bench
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - morloc
      - base
      - tasty-bench
      - text
      - filepath
