name:             morloc
version:          0.35.0-dev
homepage:         https://github.com/morloc-project/morloc
synopsis:         A multi-lingual, typed, workflow language
description:      See GitHub README <https://github.com/morloc-project/morloc#readme>
category:         Language, Compiler, Code Generation
license:          GPL-3
license-file:     LICENSE
author:           "Zebulun Arendsee" 
maintainer:       "zbwrbz@gmail.com"
github:           "morloc-project/morloc"
bug-reports:      https://github.com/morloc-project/morloc/issues
copyright:        "2020 Zebulun Arendsee"

extra-source-files:
  - README.md
  - ChangeLog.md

dependencies:
  - base >= 4.7 && < 5
  - aeson >= 1.2.4.0 && < 1.6
  - bytestring >=0.10.8.2 && <0.11
  - containers >=0.5.10.2 && <0.7
  - directory >=1.3.0.2 && <1.4
  - extra >=1.6.5 && <1.8
  - filepath >=1.4.1.2 && <1.5
  - haskell-src-meta >=0.8.0.2 && <0.9
  - megaparsec >=6.4.1 && <9.1
  - mtl >=2.2.2 && <2.3
  - parsec >=3.1.13.0 && <3.2
  - partial-order >=0.1.2.1 && <0.3
  - pretty-simple >=2.1.0.0 && <4.1
  - prettyprinter >=1.2.0.1 && <1.8
  - prettyprinter-ansi-terminal >=1.1.1.2 && <1.2
  - process >=1.6.1.0 && <1.7
  - raw-strings-qq ==1.1.*
  - safe >=0.3.17 && <0.4
  - scientific >=0.3.5.3 && <0.4
  - template-haskell >=2.12.0.0 && <2.17
  - text >=1.2.3.0 && <1.3
  - unordered-containers >=0.2.9.0 && <0.3
  - yaml >=0.11.1.2 && <0.12


default-extensions:
  - FlexibleContexts
  - OverloadedStrings
  - BangPatterns
  - GeneralizedNewtypeDeriving
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wcompat
  - -fwarn-unused-binds
  - -fwarn-unused-imports 
  - -fwarn-tabs
  - -fwarn-incomplete-uni-patterns
  - -fwarn-incomplete-record-updates
  - -fwarn-redundant-constraints
  - -fno-warn-missing-signatures
  - -fno-warn-unused-do-bind
  - -fno-warn-orphans
  - -haddock

library:
  source-dirs: library

executables:
  morloc:
    main:          Main.hs
    source-dirs:   executable
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -haddock
    dependencies:
      - morloc 
      - base >= 4.7 && < 5
      - optparse-applicative
      - text >=1.2.3.0 && <1.3

tests:
  morloc-test:
    main:          Main.hs
    source-dirs:   test-suite
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - morloc
      - base >=4.10.1.0 && <5
      - QuickCheck >=2.10.1 && <2.15
      - tasty >=1.0.1.1 && <1.3
      - tasty-golden >=2.3.1.3 && <2.4
      - tasty-hunit >=0.10.0.1 && <0.11
      - tasty-quickcheck >=0.9.2 && <0.11
