#!/usr/bin/env bash

loc -o zzz x.loc
n=$(zzz/manifold-nexus.sh apply 2> /dev/null | wc -l 2> /dev/null)
status=$?
rm -rf zzz

if [[ $status -ne 0 ]]
then
    exit 1
elif [[ $n -ne 5 ]]
then
    exit 2
else
    exit 0
fi
