#!/usr/bin/env bash
cat <<EOF > z
123	cats
34	macaws
18	unicorns
123	cats
34	macaws
18	unicorns
123	cats
34	macaws
18	unicorns
EOF

stat=0
loc -kx locout x.loc || stat=1
./manifold-nexus.py py >> y
./manifold-nexus.py r  >> y
./manifold-nexus.py sh >> y
diff z y || stat=1
&> /dev/null
rm -rf locout z y manifold-nexus.py
exit $stat
