{- |
Module      : MorlocManager.Serve
Description : Build and run immutable serve containers
Copyright   : (c) Zebulun Arendsee, 2016-2026
License     : Apache-2.0
Maintainer  : z@morloc.io

Builds minimal serve images from frozen state artifacts and runs them as
long-lived containers with the morloc-nexus router as PID 1.

@
  Serve image layer composition:

  +----------------------------------+
  | Frozen morloc state (COPY)       |  lib/, fdb/, bin/, morloc binary
  | Read-only at runtime             |
  +----------------------------------+
  | morloc-serve:\<version\>           |  Language runtimes (Python, R, C++)
  | (minimal base, no GHC/stack)     |  morloc-nexus binary
  +----------------------------------+

  Generated Dockerfile:

    FROM morloc-serve:\<version\>
    COPY state/ /home/morloc/.local/share/morloc/
    COPY morloc /usr/local/bin/morloc
    ENTRYPOINT ["morloc-nexus", "--router", \\
                "--fdb", "/home/morloc/.local/share/morloc/fdb"]
@

Serve containers expose the nexus router endpoints:

  * @GET  \/programs@        -- list all programs and commands
  * @GET  \/discover\/\<prog\>@ -- command signatures and types
  * @POST \/call\/\<prog\>\/\<cmd\>@ -- invoke a function
  * @GET  \/health@          -- pool liveness
  * @POST \/eval@            -- compose and run (requires compiler binary)
-}

module MorlocManager.Serve
  ( -- * Image building
    buildServeImage
    -- * Running
  , runServeContainer
  , stopServeContainer
  ) where

import Data.Text (Text)
import qualified Data.Text as Text
import System.Directory (createDirectoryIfMissing)
import System.FilePath ((</>), takeDirectory)
import System.Exit (ExitCode(..))
import System.IO (hPutStrLn, hFlush, stderr)
import System.Process (readProcessWithExitCode)

import MorlocManager.Types
import MorlocManager.Container

-- | Build a serve image from a frozen state tarball.
--
-- Pulls the base image from GHCR if not available locally, extracts the
-- tarball into a build context, generates a Dockerfile, and builds the
-- image. The base image defaults to
-- @ghcr.io\/morloc-project\/morloc\/morloc-serve:\<version\>@ but can be
-- overridden with @--base@.
buildServeImage
  :: ContainerEngine
  -> FilePath    -- ^ Path to state.tar.gz from freeze
  -> Text        -- ^ Image tag (e.g., @myservice:v1@)
  -> Version     -- ^ Morloc version (determines default base image)
  -> Maybe Text  -- ^ Optional base image override (@--base@)
  -> IO (Either ManagerError ())
buildServeImage engine stateTarball tag ver mBase = do
  let baseImage = case mBase of
        Just b  -> b
        Nothing -> "ghcr.io/morloc-project/morloc/morloc-serve:" <> showVersion ver
  -- Pull the base image (stderr passes through so user sees progress)
  hPutStrLn stderr $ "Pulling base image " <> Text.unpack baseImage <> "..."
  hFlush stderr
  (pullCode, _, pullErr) <- containerPull engine baseImage
  case pullCode of
    ExitFailure _ -> pure (Left (EngineError engine (exitCodeToInt pullCode) pullErr))
    ExitSuccess -> do
      let contextDir = takeDirectory stateTarball </> "serve-build"
      createDirectoryIfMissing True contextDir
      hPutStrLn stderr "Extracting frozen state..."
      hFlush stderr
      (tarCode, _, tarErr) <- readProcessWithExitCode "tar"
        ["-xzf", stateTarball, "-C", contextDir] ""
      case tarCode of
        ExitFailure _ -> pure (Left (FreezeError ("tar extract failed: " <> tarErr)))
        ExitSuccess -> do
          let dockerfilePath = contextDir </> "Dockerfile"
          hPutStrLn stderr $ "Building serve image " <> Text.unpack tag
            <> " (base: " <> Text.unpack baseImage <> ")..."
          hFlush stderr
          writeFile dockerfilePath $ unlines
            [ "# Auto-generated by morloc-manager serve-image"
            , "FROM " <> Text.unpack baseImage
            , ""
            , "# Copy frozen morloc state (modules, manifests, binaries, pools)"
            , "COPY lib/ /home/morloc/.local/share/morloc/lib/"
            , "COPY fdb/ /home/morloc/.local/share/morloc/fdb/"
            , "COPY bin/ /home/morloc/.local/share/morloc/bin/"
            , ""
            , "# Entrypoint: nexus router aggregates all installed programs"
            , "ENTRYPOINT [\"morloc-nexus\", \"--router\", \\"
            , "            \"--fdb\", \"/home/morloc/.local/share/morloc/fdb\"]"
            ]
          let buildCfg = BuildConfig
                { bcDockerfile = dockerfilePath
                , bcContext    = contextDir
                , bcTag        = tag
                , bcBuildArgs  = []
                }
          (code, _stdout, buildErr) <- containerBuild engine buildCfg
          case code of
            ExitFailure _ -> pure (Left (EngineError engine (exitCodeToInt code) buildErr))
            ExitSuccess -> do
              hPutStrLn stderr $ "Built serve image: " <> Text.unpack tag
              hFlush stderr
              pure (Right ())

-- | Run a serve container with the nexus router.
--
-- The container runs with @--read-only@ (immutable rootfs) and the
-- specified port mappings. Returns the container name for later shutdown.
runServeContainer
  :: ContainerEngine
  -> Text        -- ^ Image tag
  -> Text        -- ^ Container name
  -> [(Int,Int)] -- ^ Port mappings (host, container)
  -> IO (Either ManagerError ())
runServeContainer engine image name ports = do
  let portStr = unwords [show h <> ":" <> show c | (h, c) <- ports]
  hPutStrLn stderr $ "Starting serve container " <> Text.unpack name
    <> " on ports " <> portStr <> "..."
  hFlush stderr
  let cfg = (defaultRunConfig image)
        { rcReadOnly    = True
        , rcRemoveAfter = False  -- keep running
        , rcName        = Just name
        , rcPorts       = ports
        , rcExtraFlags  = ["-d"]  -- detached
        }
  (code, _stdout, runErr) <- containerRun engine cfg
  case code of
    ExitFailure _ -> pure (Left (EngineError engine (exitCodeToInt code) runErr))
    ExitSuccess -> do
      hPutStrLn stderr $ "Container " <> Text.unpack name <> " started"
      hFlush stderr
      pure (Right ())

-- | Stop a running serve container.
stopServeContainer :: ContainerEngine -> Text -> IO (Either ManagerError ())
stopServeContainer engine name = do
  code <- containerStop engine name
  _ <- containerRemove engine name
  case code of
    ExitFailure _ -> pure (Left (EngineError engine (exitCodeToInt code) ("Stop failed with code " <> Text.pack (show code))))
    ExitSuccess   -> pure (Right ())

-- ======================================================================
-- Internal
-- ======================================================================

-- | Extract the integer exit code from an 'ExitCode'.
exitCodeToInt :: ExitCode -> Int
exitCodeToInt ExitSuccess     = 0
exitCodeToInt (ExitFailure n) = n
