{- |
Module      : MorlocManager.Serve
Description : Build and run immutable serve containers
Copyright   : (c) Zebulun Arendsee, 2016-2026
License     : Apache-2.0
Maintainer  : z@morloc.io

Builds minimal serve images from frozen state artifacts and runs them as
long-lived containers with the morloc-nexus router as PID 1.

@
  Serve image layer composition:

  +----------------------------------+
  | Frozen morloc state (COPY)       |  lib/, fdb/, bin/, morloc binary
  | Read-only at runtime             |
  +----------------------------------+
  | morloc-full:\<version\>            |  Language runtimes, compiler, nexus
  | (already cached from install)    |  morloc-nexus binary
  +----------------------------------+

  Generated Dockerfile:

    FROM morloc-serve:\<version\>
    COPY lib/ /root/.local/share/morloc/lib/
    COPY fdb/ /root/.local/share/morloc/fdb/
    COPY bin/ /root/.local/share/morloc/bin/
    HEALTHCHECK ...
    ENTRYPOINT ["morloc-nexus", "--router", \\
                "--fdb", "/root/.local/share/morloc/fdb"]
@

Serve containers expose the nexus router endpoints:

  * @GET  \/programs@        -- list all programs and commands
  * @GET  \/discover\/\<prog\>@ -- command signatures and types
  * @POST \/call\/\<prog\>\/\<cmd\>@ -- invoke a function
  * @GET  \/health@          -- pool liveness
  * @POST \/eval@            -- compose and run (requires compiler binary)
-}

module MorlocManager.Serve
  ( -- * Image building
    buildServeImage
    -- * Running
  , runServeContainer
  , stopServeContainer
    -- * Management
  , listServeContainers
  , streamServeLogs
  ) where

import Data.Text (Text)
import qualified Data.Text as Text
import System.Directory (createDirectoryIfMissing)
import System.FilePath ((</>), takeDirectory)
import System.Exit (ExitCode(..))
import System.IO (hPutStrLn, hFlush, stderr)
import System.Process
  ( readProcessWithExitCode
  , createProcess
  , proc
  , waitForProcess
  , StdStream(..)
  , std_in, std_out, std_err
  , delegate_ctlc
  )

import MorlocManager.Types
import MorlocManager.Container
  ( RunConfig(..)
  , defaultRunConfig
  , BuildConfig(..)
  , containerRun
  , containerRunPassthrough
  , containerBuild
  , containerPull
  , containerStop
  , containerRemove
  , engineExecutable
  )

-- | Build a serve image from a frozen state tarball.
--
-- Pulls the base image from GHCR if not available locally, extracts the
-- tarball into a build context, generates a Dockerfile, and builds the
-- image. The base image defaults to
-- @ghcr.io\/morloc-project\/morloc\/morloc-full:\<version\>@ but can be
-- overridden with @--base@.
buildServeImage
  :: ContainerEngine
  -> FilePath    -- ^ Path to state.tar.gz from freeze
  -> Text        -- ^ Image tag (e.g., @myservice:v1@)
  -> Version     -- ^ Morloc version (determines default base image)
  -> Maybe Text  -- ^ Optional base image override (@--base@)
  -> IO (Either ManagerError ())
buildServeImage engine stateTarball tag ver mBase = do
  let baseImage = case mBase of
        Just b  -> b
        Nothing -> "ghcr.io/morloc-project/morloc/morloc-full:" <> showVersion ver
  -- Pull the base image (stderr passes through so user sees progress)
  hPutStrLn stderr $ "Pulling base image " <> Text.unpack baseImage <> "..."
  hFlush stderr
  (pullCode, _, pullErr) <- containerPull engine baseImage
  case pullCode of
    ExitFailure _ -> pure (Left (EngineError engine (exitCodeToInt pullCode) pullErr))
    ExitSuccess -> do
      let contextDir = takeDirectory stateTarball </> "serve-build"
      createDirectoryIfMissing True contextDir
      hPutStrLn stderr "Extracting frozen state..."
      hFlush stderr
      (tarCode, _, tarErr) <- readProcessWithExitCode "tar"
        ["-xzf", stateTarball, "-C", contextDir] ""
      case tarCode of
        ExitFailure _ -> pure (Left (FreezeError ("tar extract failed: " <> tarErr)))
        ExitSuccess -> do
          let dockerfilePath = contextDir </> "Dockerfile"
          hPutStrLn stderr $ "Building serve image " <> Text.unpack tag
            <> " (base: " <> Text.unpack baseImage <> ")..."
          hFlush stderr
          writeFile dockerfilePath $ unlines
            [ "# Auto-generated by morloc-manager serve-image"
            , "FROM " <> Text.unpack baseImage
            , ""
            , "# Copy frozen morloc state (modules, manifests, binaries, pools)"
            , "COPY lib/ /root/.local/share/morloc/lib/"
            , "COPY fdb/ /root/.local/share/morloc/fdb/"
            , "COPY bin/ /root/.local/share/morloc/bin/"
            , ""
            , "# Health check for container orchestrators"
            , "HEALTHCHECK --interval=30s --timeout=5s --retries=3 \\"
            , "  CMD wget -qO- http://localhost:8080/health || exit 1"
            , ""
            , "# Entrypoint: nexus router aggregates all installed programs"
            , "ENTRYPOINT [\"morloc-nexus\", \"--router\", \\"
            , "            \"--fdb\", \"/root/.local/share/morloc/fdb\"]"
            ]
          let buildCfg = BuildConfig
                { bcDockerfile = dockerfilePath
                , bcContext    = contextDir
                , bcTag        = tag
                , bcBuildArgs  = []
                }
          (code, _stdout, buildErr) <- containerBuild engine buildCfg
          case code of
            ExitFailure _ -> pure (Left (EngineError engine (exitCodeToInt code) buildErr))
            ExitSuccess -> do
              hPutStrLn stderr $ "Built serve image: " <> Text.unpack tag
              hFlush stderr
              pure (Right ())

-- | Run a serve container with the nexus router.
--
-- The container runs with @--read-only@ (immutable rootfs) and the
-- specified port mappings. Returns the container name for later shutdown.
runServeContainer
  :: ContainerEngine
  -> Text        -- ^ Image tag
  -> Text        -- ^ Container name
  -> [(Int,Int)] -- ^ Port mappings (host, container)
  -> IO (Either ManagerError ())
runServeContainer engine image name ports = do
  let portStr = unwords [show h <> ":" <> show c | (h, c) <- ports]
  hPutStrLn stderr $ "Starting serve container " <> Text.unpack name
    <> " on ports " <> portStr <> "..."
  hFlush stderr
  let cfg = (defaultRunConfig image)
        { rcReadOnly    = True
        , rcRemoveAfter = False  -- keep running
        , rcName        = Just name
        , rcPorts       = ports
        , rcExtraFlags  = ["-d"]  -- detached
        }
  (code, _stdout, runErr) <- containerRun engine cfg
  case code of
    ExitFailure _ -> pure (Left (EngineError engine (exitCodeToInt code) runErr))
    ExitSuccess -> do
      hPutStrLn stderr $ "Container " <> Text.unpack name <> " started"
      hFlush stderr
      pure (Right ())

-- | Stop a running serve container.
stopServeContainer :: ContainerEngine -> Text -> IO (Either ManagerError ())
stopServeContainer engine name = do
  code <- containerStop engine name
  _ <- containerRemove engine name
  case code of
    ExitFailure _ -> pure (Left (EngineError engine (exitCodeToInt code) ("Stop failed with code " <> Text.pack (show code))))
    ExitSuccess   -> pure (Right ())

-- | List running morloc serve containers.
--
-- Filters containers whose name starts with @morloc-serve-@ and prints
-- a summary table to stdout.
listServeContainers :: ContainerEngine -> IO (Either ManagerError ())
listServeContainers engine = do
  let exe = engineExecutable engine
      fmt = "{{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}"
  (code, stdout', _stderr) <- readProcessWithExitCode exe
    ["ps", "-a", "--filter", "name=morloc-serve-", "--format", fmt] ""
  case code of
    ExitFailure n -> pure (Left (EngineError engine n (Text.pack _stderr)))
    ExitSuccess -> do
      let output = strip' stdout'
      if null output
        then putStrLn "No morloc serve containers running."
        else do
          putStrLn "NAME\tIMAGE\tSTATUS\tPORTS"
          putStr output
      pure (Right ())
  where
    strip' = reverse . dropWhile isNewline . reverse
    isNewline c = c == '\n' || c == '\r'

-- | Stream logs from a serve container to the terminal.
--
-- When @follow@ is 'True', uses @--follow@ to stream new log entries
-- as they arrive (blocks until interrupted).
streamServeLogs :: ContainerEngine -> Text -> Bool -> IO (Either ManagerError ())
streamServeLogs engine name follow = do
  let exe = engineExecutable engine
      args = ["logs"] <> (if follow then ["--follow"] else []) <> [Text.unpack name]
  let cp = (proc exe args)
        { std_in  = Inherit
        , std_out = Inherit
        , std_err = Inherit
        , delegate_ctlc = True
        }
  (_, _, _, ph) <- createProcess cp
  code <- waitForProcess ph
  case code of
    ExitSuccess   -> pure (Right ())
    ExitFailure n -> pure (Left (EngineError engine n "Failed to read container logs"))

-- ======================================================================
-- Internal
-- ======================================================================

-- | Extract the integer exit code from an 'ExitCode'.
exitCodeToInt :: ExitCode -> Int
exitCodeToInt ExitSuccess     = 0
exitCodeToInt (ExitFailure n) = n
