#!/usr/bin/env bash
loc -x zzz x.loc

diff <(./manifold-nexus.py colnames) <(echo \
"Sepal.Length
Sepal.Width
Petal.Width
Species") &> /dev/null
stat=$?

rm -rf zzz manifold-nexus.py

if [[ $stat == 0 ]]
then
    exit 0
else
    exit 1
fi
