-- \|
-- Module      : Main
-- Description : Test suite entry point combining unit, property, and golden tests
import qualified System.Directory as SD
import Test.Tasty

import GoldenMakefileTests (goldenMakefileTest)
import PropertyTests (propertyTests)
import UnitTypeTests

main :: IO ()
main = do
  wd <- SD.getCurrentDirectory >>= SD.makeAbsolute
  let golden = \msg f -> goldenMakefileTest msg (wd ++ "/test-suite/golden-tests/" ++ f)
  defaultMain $
    testGroup
      "Morloc tests"
      [ unitTypeTests
      , unitValuecheckTests
      , typeOrderTests
      , typeAliasTests
      , propertyTests
      , whereTests
      , orderInvarianceTests
      , whitespaceTests
      , infixOperatorTests
      , substituteTVarTests
      , subtypeTests
      , complexityRegressionTests
      , effectSubtypeTests
      , effectSynthesisTests
      , effectErrorTests
      , namespaceErrorTests
      , typeclassTests
      , natErrorTests
      , -- -- These tests pass locally and when I run the same container that I
        -- -- use in github actions. Yet these tests freeze in an infinite loop
        -- -- with no STDERR output on github. I have no idea why. But for now I'm
        -- -- just going to comment them out. Rememver uncomment them on dev cycles
        -- -- so that they are tested somewhere, at least.
        -- , golden "specialization-1-c" "specialization-1-c"
        -- , golden "specialization-2-c" "specialization-2-c"
        -- , golden "specialization-1-py - numpy" "specialization-1-py"
        -- , golden "specialization-2-py - bytes/bytearray" "specialization-2-py"
        -- , golden "specialization-1-r" "specialization-1-r"

        -- , golden "multiprocessing-py-1" "multiprocessing-py-1"

        golden "thunk-basic" "thunk-basic"
      , golden "thunk-effects" "thunk-effects"
      , golden "thunk-do" "thunk-do"
      , golden "thunk-let" "thunk-let"
      , golden "thunk-interop" "thunk-interop"
      , golden "thunk-nullary-interop" "thunk-nullary-interop"
      , golden "thunk-force" "thunk-force"
      , golden "thunk-export" "thunk-export"
      , golden "thunk-choose" "thunk-choose"
      , golden "thunk-export-guard" "thunk-export-guard"
      , golden "thunk-guard-cross" "thunk-guard-cross"
      , golden "thunk-cross-force" "thunk-cross-force"
      , golden "thunk-eval-forall" "thunk-eval-forall"
      , golden "thunk-eval-hk" "thunk-eval-hk"
      , golden "two-module" "two-module"
      , golden "records-alias" "records-alias"
      , golden "infix" "infix"
      , golden "infix-import" "infix-import"
      , golden "infix-generic" "infix-generic"
      , golden "infix-polyglot" "infix-polyglot"
      , golden "infix-typeclass-import" "infix-typeclass-import"
      , golden "infix-typeclass-polyglot" "infix-typeclass-polyglot"
      , golden "infix-typeclass-simple" "infix-typeclass-simple"
      , golden "claude-test-1" "claude-test-1"
      , golden "claude-test-2" "claude-test-2"
      , golden "claude-test-3" "claude-test-3"
      , golden "claude-test-4" "claude-test-4"
      -- , golden "claude-test-5" "claude-test-5"
      , golden "claude-test-6" "claude-test-6"
      , golden "claude-test-7" "claude-test-7"
      , golden "claude-test-8" "claude-test-8"
      , golden "claude-test-9" "claude-test-9"
      , golden "claude-test-10" "claude-test-10"
      , golden "claude-test-11" "claude-test-11"
      , golden "claude-test-12" "claude-test-12"
      , golden "claude-test-13" "claude-test-13"
      , golden "claude-test-14" "claude-test-14"
      , golden "claude-test-15" "claude-test-15"
      , golden "claude-test-16" "claude-test-16"
      , golden "claude-test-17" "claude-test-17"
      , golden "claude-test-18" "claude-test-18"
      , golden "claude-test-19" "claude-test-19"
      , golden "claude-test-20" "claude-test-20"
      , golden "slurm-label-codegen" "slurm-label-codegen"
      , golden "let-crosslang" "let-crosslang"
      , golden "functional-data-1" "functional-data-1"
      , golden "functional-data-2" "functional-data-2"
      , golden "functional-data-3a" "functional-data-3a"
      , golden "functional-data-3b" "functional-data-3b"
      , golden "functional-data-3c" "functional-data-3c"
      , golden "functional-data-3d-py" "functional-data-3d-py"
      , golden "functional-data-3d-c" "functional-data-3d-c"
      , golden "functional-data-3d-r" "functional-data-3d-r"
      , golden "functional-data-3e" "functional-data-3e"
      , golden "functional-data-3f" "functional-data-3f"
      , golden "functional-data-4" "functional-data-4"
      , golden "functional-data-5" "functional-data-5"
      , golden "pattern-getters" "pattern-getters"
      , golden "pattern-setters" "pattern-setters"
      , golden "holes-func" "holes-func"
      , golden "holes-record" "holes-record"
      , golden "holes-simple" "holes-simple"
      , golden "type-annotations-1" "type-annotations-1"
      , golden "native-morloc-1" "native-morloc-1"
      , golden "native-morloc-2" "native-morloc-2"
      , golden "native-morloc-3" "native-morloc-3"
      , golden "native-morloc-4" "native-morloc-4"
      , golden "native-morloc-5" "native-morloc-5"
      , golden "native-morloc-6" "native-morloc-6"
      , golden "native-morloc-7" "native-morloc-7"
      , golden "native-morloc-8" "native-morloc-8"
      , golden "native-morloc-9" "native-morloc-9"
      , golden "nexus-let-pure" "nexus-let-pure"
      , golden "nexus-let-lambda" "nexus-let-lambda"
      , golden "demo-trimming" "demo-trimming"
      , golden "formatting" "formatting"
      , golden "record-docstrings" "record-docstrings"
      , golden "command-groups" "command-groups"
      , golden "typeclasses-1" "typeclasses-1"
      , golden "typeclasses-2" "typeclasses-2"
      , golden "typeclasses-3" "typeclasses-3"
      , golden "typeclasses-4" "typeclasses-4"
      , golden "typeclasses-5" "typeclasses-5"
      , golden "typeclasses-6" "typeclasses-6"
      , golden "typeclasses-7" "typeclasses-7"
      , golden "typeclasses-8" "typeclasses-8"
      , golden "typeclasses-9" "typeclasses-9"
      , golden "typeclass-stress" "typeclass-stress"
      , golden "alias-dedup-1" "alias-dedup-1"
      , golden "alias-no-cross-instance" "alias-no-cross-instance"
      , golden "alias-concrete-bugs" "alias-concrete-bugs"
      , golden "poly-list-1" "poly-list-1"
      , golden "higher-kinded-types" "higher-kinded-types"
      , golden "string-encoding" "string-encoding"
      , golden "string-encoding-utf8" "string-encoding-utf8"
      , golden "string-json-parsing" "string-json-parsing"
      , golden "string-multiline" "string-multiline"
      , golden "string-interpolation" "string-interpolation"
      , golden "string-escape" "string-escape"
      , golden "file-input-py" "file-input-py"
      , golden "file-input-c" "file-input-c"
      , golden "file-input-r" "file-input-r"
      , golden "packer-definitions-1" "packer-definitions-1"
      , golden "packer-definitions-2" "packer-definitions-2"
      , golden "packer-definitions-3" "packer-definitions-3"
      , golden "packer-definitions-4" "packer-definitions-4"
      , golden "packer-definitions-5" "packer-definitions-5"
      , golden "import-1" "import-1"
      , golden "import-2" "import-2"
      , -- tests the bug solved involving the lambdaScope function in
        -- Generate.hs:reserialize. See that commit message.
        golden "edge-cases-1" "edge-cases-1"
      , golden "edge-cases-2" "edge-cases-2"
      , golden "type-synthesis-1" "type-synthesis-1"
      , golden "type-synthesis-2" "type-synthesis-2"
      , golden "argument-form-1-c" "argument-form-1-c"
      , golden "argument-form-1-py" "argument-form-1-py"
      , golden "argument-form-1-r" "argument-form-1-r"
      , golden "argument-form-2-c" "argument-form-2-c"
      , golden "argument-form-2-py" "argument-form-2-py"
      , golden "argument-form-2-r" "argument-form-2-r"
      , -- see github issue #7
        golden "argument-form-3-c" "argument-form-3-c"
      , golden "argument-form-3-py" "argument-form-3-py"
      , golden "argument-form-3-r" "argument-form-3-r"
      , golden "composition" "composition"
      , golden "generic-hofs-1" "generic-hofs-1"
      , golden "generic-hofs-2" "generic-hofs-2"
      , golden "eta-reduction-1" "eta-reduction-1"
      , golden "eta-reduction-2" "eta-reduction-2"
      , golden "eta-reduction-3" "eta-reduction-3"
      , golden "eta-reduction-4" "eta-reduction-4"
      , golden "eta-reduction-5" "eta-reduction-5"
      , golden "eta-reduction-6" "eta-reduction-6"
      , golden "eta-reduction-7" "eta-reduction-7"
      , golden "eta-reduction-8-py" "eta-reduction-8-py"
      , golden "eta-reduction-8-cpp" "eta-reduction-8-cpp"
      , golden "path-shadowing-c" "path-shadowing-c"
      , golden "path-shadowing-py" "path-shadowing-py"
      , golden "path-shadowing-r" "path-shadowing-r"
      , golden "local-import-root-py" "local-import-root-py"
      , golden "local-import-cousin-py" "local-import-cousin-py"
      , golden "local-import-nested-py" "local-import-nested-py"
      , golden "argument-form-4-c" "argument-form-4-c"
      , golden "argument-form-4-py" "argument-form-4-py"
      , golden "argument-form-4-r" "argument-form-4-r"
      , golden "argument-form-5-c" "argument-form-5-c"
      , golden "argument-form-5-py" "argument-form-5-py"
      , golden "argument-form-5-r" "argument-form-5-r"
      , golden "argument-form-6-c" "argument-form-6-c"
      , golden "argument-form-6-py" "argument-form-6-py"
      , golden "argument-form-6-r" "argument-form-6-r"
      , golden "argument-form-7-c" "argument-form-7-c"
      , golden "argument-form-7-py" "argument-form-7-py"
      , golden "argument-form-7-r" "argument-form-7-r"
      , golden "argument-form-8-c" "argument-form-8-c"
      , golden "argument-form-8-py" "argument-form-8-py"
      , golden "argument-form-8-r" "argument-form-8-r"
      , golden "interop-1-py" "interop-1-py"
      , golden "interop-1-r" "interop-1-r"
      , golden "interop-2" "interop-2"
      , -- 3a
        golden "interop-3a-cp" "interop-3a-cp"
      , golden "interop-3a-pr" "interop-3a-pr"
      , golden "interop-3a-rc" "interop-3a-rc"
      , golden "interop-3a-pp" "interop-3a-pp"
      , -- 3b
        golden "interop-3b-cp" "interop-3b-cp"
      , golden "interop-3b-pr" "interop-3b-pr"
      , golden "interop-3b-rc" "interop-3b-rc"
      , golden "interop-3b-pp" "interop-3b-pp"
      , -- 3c
        golden "interop-3c-cp" "interop-3c-cp"
      , golden "interop-3c-pr" "interop-3c-pr"
      , golden "interop-3c-rc" "interop-3c-rc"
      , golden "interop-3c-pp" "interop-3c-pp"
      , -- 3d
        golden "interop-3d-cp" "interop-3d-cp"
      , golden "interop-3d-pr" "interop-3d-pr"
      , golden "interop-3d-rc" "interop-3d-rc"
      , golden "interop-3d-pp" "interop-3d-pp"
      , -- 3e
        golden "interop-3e-cp" "interop-3e-cp"
      , golden "interop-3e-pr" "interop-3e-pr"
      , golden "interop-3e-rc" "interop-3e-rc"
      , golden "interop-3e-pp" "interop-3e-pp"
      , -- 3f - test serialization type bug
        golden "interop-3f" "interop-3f"
      , -- other random interop tests (I should kill them)
        golden "interop-4" "interop-4"
      , golden "interop-5" "interop-5"
      , golden "interop-6" "interop-6"
      , golden "interop-7" "interop-7"
      , golden "interop-8-r-to-c" "interop-8-r-to-c"
      , golden "interop-8-r-to-py" "interop-8-r-to-py"
      , golden "interop-8-py-to-r" "interop-8-py-to-r"
      , golden "interop-9" "interop-9"
      , golden "interop-10" "interop-10"
      , golden "interop-11" "interop-11"
      , golden "manifold-form-0" "manifold-form-0"
      , golden "manifold-form-0x" "manifold-form-0x"
      , golden "manifold-form-1" "manifold-form-1"
      , golden "manifold-form-2" "manifold-form-2"
      , golden "manifold-form-2x" "manifold-form-2x"
      , golden "manifold-form-3" "manifold-form-3"
      , golden "manifold-form-3x" "manifold-form-3x"
      , golden "manifold-form-4_c" "manifold-form-4_c"
      , golden "manifold-form-4_py" "manifold-form-4_py"
      , golden "manifold-form-4_r" "manifold-form-4_r"
      , golden "manifold-form-5_c" "manifold-form-5_c"
      , golden "manifold-form-5_py" "manifold-form-5_py"
      , golden "manifold-form-5_r" "manifold-form-5_r"
      , golden "manifold-form-6_c" "manifold-form-6_c"
      , golden "manifold-form-6_py" "manifold-form-6_py"
      , golden "manifold-form-6_r" "manifold-form-6_r"
      , -- see github issue #9
        golden "manifold-form-7_c" "manifold-form-7_c"
      , golden "manifold-form-7_py" "manifold-form-7_py"
      , golden "manifold-form-7_r" "manifold-form-7_r"
      , -- test records
        golden "records-primitive" "records-primitive"
      , golden "records-complex-1" "records-complex-1"
      , golden "records-complex-2" "records-complex-2"
      , golden "records-nested" "records-nested"
      , golden "records-alias" "records-alias"
      , golden "selection-1" "selection-1"
      , golden "selection-2" "selection-2"
      , golden "selection-3" "selection-3"
      , golden "selection-4" "selection-4"
      , -- import two instances in one languages for a function
        -- this is also a test of a function that is defind in a local file
        -- -- With the new stricter implementation, these tests no longer pass
        -- -- They can be reinstated when the morloc compiler learns to
        -- -- distinguish the functions reasonably
        -- , golden "multiple-instances-1-c" "multiple-instances-1-c"
        -- , golden "multiple-instances-1-py" "multiple-instances-1-py"
        -- , golden "multiple-instances-1-r" "multiple-instances-1-r"
        -- multiple sources and a declaration
        golden "multiple-instances-2-c" "multiple-instances-2-c"
      , golden "multiple-instances-2-py" "multiple-instances-2-py"
      , golden "multiple-instances-2-r" "multiple-instances-2-r"
      , golden "multi-lang-mempty-py" "multi-lang-mempty-py"
      , golden "bare-selector-args" "bare-selector-args"
      , golden "bare-selector-chain" "bare-selector-chain"
      , -- tests of module forms
        -- where *-sid
        --   s - number of sourced instances
        --   i - number of imported instances
        --   d - number of declared instances
        golden "module-form-00n" "module-form-00n"
      , golden "module-form-011" "module-form-011"
      , golden "module-form-01n" "module-form-01n"
      , golden "module-form-0n0" "module-form-0n0"
      , golden "module-form-0n1" "module-form-0n1"
      , golden "module-form-101" "module-form-101"
      , golden "module-form-10n" "module-form-10n"
      , golden "module-form-110" "module-form-110"
      , golden "module-form-111" "module-form-111"
      , golden "module-form-1n0" "module-form-1n0"
      , golden "module-form-n00" "module-form-n00"
      , golden "module-form-n01" "module-form-n01"
      , golden "module-form-n10" "module-form-n10"
      , -- tests of serialization
        -- , golden "c  S" "serial-form-1-c"
        -- , golden "py S" "serial-form-1-py"
        -- , golden "r  S" "serial-form-1-r"
        golden "C serial-form-2-c" "serial-form-2-c"
      , golden "C serial-form-2-py" "serial-form-2-py"
      , golden "C serial-form-2-r" "serial-form-2-r"
      , -- , golden "c  R" "serial-form-3-c"
        -- , golden "py R" "serial-form-3-py"
        -- , golden "r  R" "serial-form-3-r"
        -- outer simple type
        golden "S(S) serial-form-4-c" "serial-form-4-c"
      , golden "S(S) serial-form-4-py" "serial-form-4-py"
      , golden "S(S) serial-form-4-r" "serial-form-4-r"
      , golden "S(C) serial-form-5-c" "serial-form-5-c"
      , golden "S(C) serial-form-5-py" "serial-form-5-py"
      , golden "S(C) serial-form-5-r" "serial-form-5-r"
      , golden "S(R) serial-form-6-c" "serial-form-6-c"
      , golden "S(R) serial-form-6-py" "serial-form-6-py"
      , golden "S(R) serial-form-6-r" "serial-form-6-r"
      , -- outer constructed type
        golden "C(S) serial-form-7-c" "serial-form-7-c"
      , golden "C(S) serial-form-7-py" "serial-form-7-py"
      , golden "C(S) serial-form-7-r" "serial-form-7-r"
      , golden "C(C) serial-form-8-c" "serial-form-8-c"
      , -- , golden "C(C) serial-form-8-py" "serial-form-8-py"
        golden "C(C) serial-form-8-r" "serial-form-8-r"
      , golden "C(R) serial-form-9-c" "serial-form-9-c"
      , golden "C(R) serial-form-9-py" "serial-form-9-py"
      , golden "C(R) serial-form-9-r" "serial-form-9-r"
      , -- outer record type
        golden "R(S) serial-form-10-c" "serial-form-10-c"
      , golden "R(S) serial-form-10-py" "serial-form-10-py"
      , golden "R(S) serial-form-10-r" "serial-form-10-r"
      , golden "R(C) serial-form-11-c" "serial-form-11-c"
      , golden "R(C) serial-form-11-py" "serial-form-11-py"
      , golden "R(C) serial-form-11-r" "serial-form-11-r"
      , golden "R(R) serial-form-12-c" "serial-form-12-c"
      , golden "R(R) serial-form-12-py" "serial-form-12-py"
      , golden "R(R) serial-form-12-r" "serial-form-12-r"
      , -- table handling
        golden "table-1-c" "table-1-c"
      , golden "table-1-py" "table-1-py"
      , golden "table-1-r" "table-1-r"
      , golden "table-2-c" "table-2-c"
      , golden "table-2-py" "table-2-py"
      , golden "table-2-r" "table-2-r"
      , -- object handling
        golden "object-1-c" "object-1-c"
      , golden "object-1-py" "object-1-py"
      , golden "object-1-r" "object-1-r"
      , -- scoping
        golden "scoping-1" "scoping-1"
      , golden "scoping-2" "scoping-2"
      , golden "scoping-3" "scoping-3"
      , golden "scoping-4" "scoping-4"
      , golden "scoping-5" "scoping-5"
      , golden "scoping-6" "scoping-6"
      , golden "scoping-7" "scoping-7"
      , golden "scoping-8" "scoping-8"
      , golden "scoping-9" "scoping-9"
      , golden "scoping-10" "scoping-10"
      , golden "scoping-11" "scoping-11"
      , golden "scoping-12" "scoping-12"
      , golden "scoping-13" "scoping-13"
      , -- type alias transitive resolution
        golden "type-alias-transitive" "type-alias-transitive"
      , -- type identities
        golden "type-identities-c" "type-identities-c"
      , -- testing packet transmission
        golden "packets-large (wait ~10s)" "packets-large"
      , golden "packets-interop (wait ~10s)" "packets-interop"
      , -- many tests of higher-order functions
        golden "hofs-1" "hofs-1"
      , -- test errors
        golden "errors (wait ~10s)" "errors"
      , golden "feature-integration-1" "feature-integration-1"
      , golden "let-expressions" "let-expressions"
      , golden "guards-py" "guards-py"
      , golden "guards-cpp" "guards-cpp"
      , golden "guards-r" "guards-r"
      , golden "guards-let-py" "guards-let-py"
      , golden "guards-let-cpp" "guards-let-cpp"
      , golden "guards-let-r" "guards-let-r"
      , golden "guards-inline-cpp" "guards-inline-cpp"
      , golden "recursion-direct-py" "recursion-direct-py"
      , golden "recursion-direct-cpp" "recursion-direct-cpp"
      , golden "recursion-direct-r" "recursion-direct-r"
      , golden "recursion-mutual-py" "recursion-mutual-py"
      , golden "recursion-mutual-cpp" "recursion-mutual-cpp"
      , golden "recursion-mutual-r" "recursion-mutual-r"
      , golden "recursion-cross-py-cpp" "recursion-cross-py-cpp"
      , golden "recursion-cross-r-cpp" "recursion-cross-r-cpp"
      , golden "recursion-helper-py" "recursion-helper-py"
      , golden "recursion-helper-cpp" "recursion-helper-cpp"
      , golden "recursion-thunk-py" "recursion-thunk-py"
      , golden "recursion-thunk-helper-cpp" "recursion-thunk-helper-cpp"
      , -- optional type tests
        golden "optional-py" "optional-py"
      , golden "optional-cpp" "optional-cpp"
      , golden "optional-r" "optional-r"
      , golden "optional-json" "optional-json"
      , golden "optional-interop-cp" "optional-interop-cp"
      , golden "optional-interop-pr" "optional-interop-pr"
      , golden "optional-interop-rc" "optional-interop-rc"
      , golden "optional-records-py" "optional-records-py"
      , golden "optional-records-cpp" "optional-records-cpp"
      , golden "optional-records-r" "optional-records-r"
      , -- optional coercion tests (a -> ?a)
        golden "optional-coerce-py" "optional-coerce-py"
      , golden "optional-coerce-cpp" "optional-coerce-cpp"
      , golden "optional-coerce-interop" "optional-coerce-interop"
      , -- effect coercion tests (a -> <IO> a)
        golden "effect-coerce-py" "effect-coerce-py"
      , golden "effect-coerce-cpp" "effect-coerce-cpp"
      , -- multi-label and subtyping effect tests
        golden "effect-multi-label-py" "effect-multi-label-py"
      , golden "effect-subtype-py" "effect-subtype-py"
      , golden "effect-error-cpp" "effect-error-cpp"
      , golden "effect-accumulate-py" "effect-accumulate-py"
      , -- inline force operator (!) tests
        golden "force-inline-basic" "force-inline-basic"
      , -- intrinsic tests
        golden "intrinsic-hash" "intrinsic-hash"
      , golden "intrinsic-constants" "intrinsic-constants"
      , golden "intrinsic-show-read" "intrinsic-show-read"
      , golden "intrinsic-show-read-nexus" "intrinsic-show-read-nexus"
      , golden "intrinsic-show-ho-r" "intrinsic-show-ho-r"
      , -- parser stress test: precedence, parentheses, negatives, numeric literals, getters
        golden "parser-stress" "parser-stress"
      , -- stdout flush test: verify Python pool stdout is flushed before shutdown
        golden "stdout-flush-py" "stdout-flush-py"
      , -- namespace import tests
        golden "namespace-basic" "namespace-basic"
      , golden "namespace-selective" "namespace-selective"
      , golden "namespace-separate-impls" "namespace-separate-impls"
      , golden "namespace-disambiguation" "namespace-disambiguation"
      , golden "namespace-ns-composition" "namespace-ns-composition"
      , golden "namespace-ns-hof" "namespace-ns-hof"
      , golden "namespace-ns-let" "namespace-ns-let"
      , golden "namespace-ns-shadow" "namespace-ns-shadow"
      , golden "namespace-ns-multi" "namespace-ns-multi"
      , golden "namespace-ns-same-func-name" "namespace-ns-same-func-name"
      , golden "namespace-ns-unqualified" "namespace-ns-unqualified"
      , golden "namespace-ns-exported" "namespace-ns-exported"
      , golden "namespace-ns-reexport" "namespace-ns-reexport"
      , golden "namespace-ns-nested-getter" "namespace-ns-nested-getter"
      , golden "namespace-ns-guard" "namespace-ns-guard"
      , golden "namespace-ns-double-import" "namespace-ns-double-import"
      , -- %inline pragma tests
        golden "inline-op-py" "inline-op-py"
      , golden "inline-func-py" "inline-func-py"
      , golden "inline-typeclass-py" "inline-typeclass-py"
      , golden "inline-ho-py" "inline-ho-py"
      , golden "inline-op-ho-py" "inline-op-ho-py"
      , golden "inline-deep-py" "inline-deep-py"
      , golden "inline-mixed-py" "inline-mixed-py"
      , golden "inline-block-py" "inline-block-py"
      , golden "inline-old-style-py" "inline-old-style-py"
      , golden "inline-cross-lang" "inline-cross-lang"
      , -- bare operators in old-style source declarations
        golden "source-old-op-py" "source-old-op-py"
      , -- eval mode restriction tests
        golden "eval-restrict-source" "eval-restrict-source"
      , -- memory alignment tests (document misalignment bugs in voidstar format)
        golden "memory-optional-double-cpp" "memory-optional-double-cpp"
      , golden "memory-optional-double-py" "memory-optional-double-py"
      , golden "memory-record-pack-cpp" "memory-record-pack-cpp"
      , golden "memory-record-pack-py" "memory-record-pack-py"
      , golden "memory-interop-misalign-cp" "memory-interop-misalign-cp"
      , golden "memory-nested-misalign-cpp" "memory-nested-misalign-cpp"
      , golden "memory-nested-misalign-py" "memory-nested-misalign-py"
      , golden "memory-split-block-cpp" "memory-split-block-cpp"
      , -- arrow immutable table tests (large table passed by reference into map)
        golden "arrow-immutable-pr" "arrow-immutable-pr"
      , golden "arrow-immutable-rp" "arrow-immutable-rp"
      , golden "arrow-immutable-cp" "arrow-immutable-cp"
      , golden "arrow-immutable-pc" "arrow-immutable-pc"
      , -- dense tensor tests
        golden "tensor-nexus-cpp" "tensor-nexus-cpp"
      , golden "tensor-table-cpp" "tensor-table-cpp"
      , golden "tensor-cp" "tensor-cp"
      , golden "tensor-pc" "tensor-pc"
      , golden "tensor-pr" "tensor-pr"
      , golden "tensor-rp" "tensor-rp"
      , golden "tensor-comprehensive-cpp" "tensor-comprehensive-cpp"
      , golden "tensor-comprehensive-cross" "tensor-comprehensive-cross"
      , golden "tensor-dimensions" "tensor-dimensions"
      , -- nat-parameterized type tests
        golden "nat-typecheck" "nat-typecheck"
      ]
