{-# LANGUAGE OverloadedStrings #-}

-- |
-- Module      : RustPoolBuildTests
-- Description : Unit tests for the Rust pool's cargo build decisions
--
-- A Rust pool starts from the environment's Cargo.lock: the lock persisted
-- with the runtime's Rust workspace, extended by every crate an earlier pool
-- in this environment resolved. When that lock already pins every crate the
-- pool needs, cargo is run --offline; otherwise cargo reaches the registry for
-- the missing crates and the pins it adds are merged back. The pool's release
-- profile (lto, opt-level) comes from the @rust:@ build parameters, validated
-- against Cargo's own vocabulary. These tests pin down the coverage check, the
-- lock merge, and the profile resolution.
module RustPoolBuildTests
  ( rustPoolBuildTests
  ) where

import Data.Text (Text)
import qualified Data.Text as T
import Test.Tasty (TestTree, testGroup)
import Test.Tasty.HUnit

import qualified Data.Map as Map
import Morloc.Build.CargoLock (lockCoversCrates, mergeCargoLocks)
import Morloc.Build.Params (LangParams, parseLangParamList)
import Morloc.CodeGenerator.Pools.CAbi.Members.Rust (RustProfile (..), resolveRustProfile)

rustParams :: [(Text, Text)] -> LangParams
rustParams kvs = Map.singleton "rust" (Map.fromList kvs)

assertLeft :: Show a => Either e a -> Assertion
assertLeft e = case e of
  Left _ -> return ()
  Right v -> assertFailure ("expected rejection, got " ++ show v)

-- | A lock in cargo's own layout: a header, then one @[[package]]@ table per
-- crate, tables separated by a blank line, a single newline at the end.
lock :: [(Text, Text)] -> Text
lock pkgs = lockHeader <> T.intercalate "\n" [block n v | (n, v) <- pkgs]
  where
    block n v = T.unlines ["[[package]]", "name = \"" <> n <> "\"", "version = \"" <> v <> "\""]

lockHeader :: Text
lockHeader = T.unlines ["# This file is automatically @generated by Cargo.", "version = 4", ""]

rustPoolBuildTests :: TestTree
rustPoolBuildTests =
  testGroup
    "Rust pool build"
    [ lockCoverageTests
    , lockMergeTests
    , profileTests
    , envParamListTests
    ]

profileTests :: TestTree
profileTests =
  testGroup
    "release profile from rust: build parameters"
    [ testCase "defaults are cross-crate thin LTO at opt-level 2" $
        resolveRustProfile Map.empty @?= Right (RustProfile {rpLto = "\"thin\"", rpOptLevel = "2"})
    , testCase "lto accepts every Cargo spelling, quoting the string forms" $ do
        resolveRustProfile (rustParams [("lto", "off")]) @?= Right (RustProfile "\"off\"" "2")
        resolveRustProfile (rustParams [("lto", "thin")]) @?= Right (RustProfile "\"thin\"" "2")
        resolveRustProfile (rustParams [("lto", "fat")]) @?= Right (RustProfile "\"fat\"" "2")
        resolveRustProfile (rustParams [("lto", "false")]) @?= Right (RustProfile "false" "2")
        resolveRustProfile (rustParams [("lto", "true")]) @?= Right (RustProfile "true" "2")
    , testCase "opt-level accepts 0-3, s and z" $ do
        resolveRustProfile (rustParams [("opt-level", "0")]) @?= Right (RustProfile "\"thin\"" "0")
        resolveRustProfile (rustParams [("opt-level", "3")]) @?= Right (RustProfile "\"thin\"" "3")
        resolveRustProfile (rustParams [("opt-level", "s")]) @?= Right (RustProfile "\"thin\"" "\"s\"")
        resolveRustProfile (rustParams [("opt-level", "z")]) @?= Right (RustProfile "\"thin\"" "\"z\"")
    , testCase "unknown lto value is rejected" $
        assertLeft (resolveRustProfile (rustParams [("lto", "yes")]))
    , testCase "unknown opt-level is rejected" $ do
        assertLeft (resolveRustProfile (rustParams [("opt-level", "4")]))
        assertLeft (resolveRustProfile (rustParams [("opt-level", "")]))
    , testCase "other languages' parameters are ignored" $
        resolveRustProfile (Map.singleton "cpp" (Map.fromList [("lto", "yes")])) @?= Right (RustProfile "\"thin\"" "2")
    ]

envParamListTests :: TestTree
envParamListTests =
  testGroup
    "MORLOC_LANG_PARAMS list syntax"
    [ testCase "semicolon-separated entries" $
        parseLangParamList "rust:lto=off;cpp:flags=-O3" @?= Right [("rust", "lto", "off"), ("cpp", "flags", "-O3")]
    , testCase "empty string is no parameters" $
        parseLangParamList "" @?= Right []
    , testCase "empty entries from stray separators are dropped" $
        parseLangParamList ";rust:lto=off;;" @?= Right [("rust", "lto", "off")]
    , testCase "a value may contain = and :" $
        parseLangParamList "cpp:flags=-DFOO=a:b" @?= Right [("cpp", "flags", "-DFOO=a:b")]
    , testCase "a malformed entry rejects the whole list" $
        assertLeft (parseLangParamList "rust:lto=off;nonsense")
    ]

lockMergeTests :: TestTree
lockMergeTests =
  testGroup
    "cargo lock merge"
    [ testCase "a crate only the pool resolved is added" $
        mergeCargoLocks (lock [("libc", "0.2.1")]) (lock [("libc", "0.2.1"), ("ndarray", "0.16.1")])
          @?= lock [("libc", "0.2.1"), ("ndarray", "0.16.1")]
    , testCase "the base pin wins for a crate both name" $
        mergeCargoLocks (lock [("arrow", "58.1.0")]) (lock [("arrow", "58.4.0"), ("ndarray", "0.16.1")])
          @?= lock [("arrow", "58.1.0"), ("ndarray", "0.16.1")]
    , testCase "merging a lock into itself changes nothing" $
        mergeCargoLocks (lock [("a", "1"), ("b", "2")]) (lock [("a", "1"), ("b", "2")]) @?= lock [("a", "1"), ("b", "2")]
    , testCase "packages are kept sorted by name" $
        mergeCargoLocks (lock [("m", "1")]) (lock [("z", "1"), ("a", "1")]) @?= lock [("a", "1"), ("m", "1"), ("z", "1")]
    , testCase "two base versions of one crate both survive" $
        -- syn 2 and syn 3 legitimately coexist; the pool's syn entry is a
        -- duplicate by name and is dropped, the base pair stays intact.
        mergeCargoLocks (lock [("syn", "2.0.1"), ("syn", "3.0.5")]) (lock [("syn", "2.0.1")])
          @?= lock [("syn", "2.0.1"), ("syn", "3.0.5")]
    , testCase "an empty environment lock yields the base" $
        mergeCargoLocks (lock [("libc", "0.2.1")]) "" @?= lock [("libc", "0.2.1")]
    , testCase "the header and trailing sections come from the base only" $
        let trailer = "\n[[patch.unused]]\nname = \"foo\"\nversion = \"1.0.0\"\n"
         in mergeCargoLocks (lock [("libc", "0.2.1")] <> trailer) (lock [("ndarray", "0.16.1")] <> "\n[[patch.unused]]\nname = \"bar\"\nversion = \"1\"\n")
              @?= lock [("libc", "0.2.1"), ("ndarray", "0.16.1")] <> trailer
    , testCase "a lock with no header takes the base header" $
        mergeCargoLocks (lock [("libc", "0.2.1")]) "[[package]]\nname = \"ndarray\"\nversion = \"0.16.1\"\n"
          @?= lock [("libc", "0.2.1"), ("ndarray", "0.16.1")]
    ]

lockCoverageTests :: TestTree
lockCoverageTests =
  testGroup
    "cargo lock coverage"
    [ testCase "no external crates is always covered" $
        assertBool "" (lockCoversCrates (lock [("libc", "0.2.1")]) [])
    , testCase "every crate present" $
        assertBool "" (lockCoversCrates (lock [("libc", "0.2.1"), ("ndarray", "0.16.1")]) ["ndarray", "libc"])
    , testCase "one crate missing" $
        assertBool "" (not (lockCoversCrates (lock [("libc", "0.2.1")]) ["ndarray"]))
    , testCase "a dependency-list mention is not a package entry" $
        -- `dependencies = [ "ndarray" ]` names the crate but does not pin it.
        assertBool "" (not (lockCoversCrates (lock [("libc", "0.2.1")] <> "dependencies = [\n \"ndarray\",\n]\n") ["ndarray"]))
    , testCase "prefix of a name does not match" $
        assertBool "" (not (lockCoversCrates (lock [("ndarray-rand", "0.15.0")]) ["ndarray"]))
    , testCase "empty lock covers nothing" $
        assertBool "" (not (lockCoversCrates "" ["libc"]))
    ]
