#!/usr/bin/env bash

loc -x tst x.loc &> /dev/null
./manifold-nexus.py map &> /dev/null
status=
if [[ -f f-cars.pdf && -f f-mtcars.pdf ]]
then
    status=0
else
    status=1
fi
rm -rf tst manifold-nexus.py *pdf

exit $status
