all:
	morloc make foo.loc
	./nexus.pl f1 > obs.txt
	./nexus.pl f2 42 >> obs.txt
	./nexus.pl f3 >> obs.txt
	./nexus.pl f4 >> obs.txt
	./nexus.pl f5 >> obs.txt
	./nexus.pl f6 >> obs.txt
	./nexus.pl f7 >> obs.txt
	./nexus.pl f8 >> obs.txt
	./nexus.pl f9 >> obs.txt
	./nexus.pl f10 >> obs.txt

clean:
	rm -f nexus* pool*
