group_defaults:
  benchmark: false
  remote: null
  cache: null

groups:
  large:
    benchmark: true
    remote:
      threads: 32
      mem: 128
      gpus: 0
      time: "3-00:00:00"
    cache: "arg_hash"
  small:
    remote:
      threads: 16
      mem: 8
      time: "0-01:00:00"
    cache: "arg_hash"
