#!/usr/bin/env bash
cat <<EOF > z
["this is an example text", "that covers", "several", "lines"]
42
0.42
"fourty-two"
true
EOF
stat=0
loc -kx locout x.loc || stat=1
./manifold-nexus.py Text   >  y
./manifold-nexus.py Int    >> y
./manifold-nexus.py Num    >> y
./manifold-nexus.py String >> y
./manifold-nexus.py Bool   >> y
diff z y || stat=1
&> /dev/null
rm -rf locout z y manifold-nexus.py
exit $stat
