.PHONY: 1
1:
	loc -kt -o hello_world -x pools 1_hello_world.loc

.PHONY: 2
2:
	loc -kt -o composition -x pools 2_composition.loc

.PHONY: 3
3:
	loc -kt -o modifiers -x pools 3_modifiers.loc

.PHONY: 4
4:
	loc -kt -o hooks -x pools 4_hooks.loc

.PHONY: 5
5:
	loc -kt -o types -x pools 5_types.loc

.PHONY: 6
6:
	loc -kt -o filesize -x pools 6_filesize.loc

.PHONY: clean
clean:
	rm -rf pools hello_world composition modifiers \
		hooks *pdf manifold-nexus.py \
		sample* results types filesize times
