#!/usr/bin/env python3
"""Generate the per-language programs, Makefile and exp.txt of this golden.

Run from this directory after editing a shape: `python3 gen.py`.
"""

LANGS = ["py", "cpp", "rust", "r"]

IMPORT = {"py": "root-py", "cpp": "root-cpp", "rust": "root-rust", "r": "root-r"}
SOURCE = {"py": "Py", "cpp": "Cpp", "rust": "Rust", "r": "R"}
HOSTFILE = {"py": "host.py", "cpp": "host.hpp", "rust": "host.rs", "r": "host.R"}
RECORD = {"py": ("dict", "dict"), "cpp": ("Ops", "Wrap"), "rust": ("Ops", "Wrap"), "r": ("list", "list")}
MAPMOD = {"py": "map-py", "cpp": "map-cpp", "r": "map-r"}

ALL = set(LANGS)

# Added to each helper's lambdas so the helper is larger than the size above
# which a definition is compiled once and called rather than expanded at its
# use: a container built by a helper then reaches the host through a call.
PAD = " + 0 * (1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 + 12 + 13 + 14 + 15 + 16)"


# (name, languages, definition, expected stdout)
#
# `eff p i` appends one byte to counter file `p` and returns
# 100 * (bytes so far) + i, so a result shows both the argument the host
# passed and how many times the effect has run.
SHAPES = [
    ("recHelper", ALL, """
recHelper :: Str -> <IO> Str
recHelper p = hOps (ops p) 5""", "ok 105"),
    ("recLoop", ALL, """
loop :: Int -> Ops -> <IO> Str
loop n o
  ? n <= 0 = hOps o 5
  : loop (n - 1) o

recLoop :: Str -> <IO> Str
recLoop p = loop 2 (ops p)""", "ok 105"),
    ("getter", ALL, """
getter :: Str -> <IO> Str
getter p = hApply (.get (ops p)) 5""", "ok 105"),
    ("nested", ALL, """
nested :: Str -> <IO> Str
nested p = hWrap { inner = ops p } 5""", "ok 105"),
    ("tupHelper", ALL, """
pair :: Str -> (Int -> <IO> Int, Int)
pair p = (\\i -> eff p (i""" + PAD + """), 5)

tupHelper :: Str -> <IO> Str
tupHelper p = hTup (pair p)""", "ok 105"),
    ("listHelper", ALL, """
fns :: Str -> [Int -> <IO> Int]
fns p = [\\i -> eff p (i""" + PAD + """), \\i -> eff p (i + 1)]

listHelper :: Str -> <IO> Str
listHelper p = hList (fns p) 5""", "ok 311"),
    ("optLiteral", ALL, """
optLiteral :: Str -> <IO> Str
optLiteral p = hOpt (\\i -> eff p i) 5""", "ok 105"),
    ("optHelper", ALL, """
mopt :: Str -> ?(Int -> <IO> Int)
mopt p = \\i -> eff p (i""" + PAD + """)

optHelper :: Str -> <IO> Str
optHelper p = hOpt (mopt p) 5""", "ok 105"),
    ("mapHelper", {"py", "cpp", "r"}, """
table :: Str -> Map Str (Int -> <IO> Int)
table p = fromList [("a", \\i -> eff p (i""" + PAD + """))]

mapHelper :: Str -> <IO> Str
mapHelper p = hMap (table p) 5""", "ok 105"),
    ("suspOps", ALL, """
later :: Str -> <IO> Ops
later p = do
  _ <- tick p
  ops p

suspOps :: Str -> <IO> Str
suspOps p = hSuspOps (later p) 5""", "ok 205"),
    ("hostRec", ALL, """
hostRec :: Str -> <IO> Int
hostRec p = do
  o <- hMakeOps 1
  (.get o) 5""", "6"),
    ("listRoundTrip", ALL, """
listRoundTrip :: Str -> <IO> Str
listRoundTrip p = do
  fs <- hMakeList 2
  hList fs 5""", "ok 17"),
    ("roundTrip", ALL, """
roundTrip :: Str -> <IO> Str
roundTrip p = do
  o <- hMakeOps 1
  hOps o 5""", "ok 6"),
    ("aliased", ALL, """
aliased :: Str -> <IO> Str
aliased p = do
  let o = ops p
  x <- (.get o) 1
  s <- hOps o 5
  s <> " " <> @show x""", "ok 205 101"),
    ("cbRet", ALL, """
cbRet :: Str -> <IO> Str
cbRet p = hCbRet (\\k -> { get = \\i -> eff p (i + k) }) 5""", "ok 110"),
    ("cbParam", ALL, """
useGet :: Ops -> <IO> Int
useGet o = (.get o) 3

cbParam :: Str -> <IO> Str
cbParam p = hCbParam useGet""", "ok 30"),
]


def program(lang):
    shapes = [s for s in SHAPES if lang in s[1]]
    names = ", ".join(s[0] for s in shapes)
    src = SOURCE[lang]
    ops_t, wrap_t = RECORD[lang]
    lines = [
        "-- Effectful functions inside containers crossing a host boundary.",
        "-- A host calls `f(x)` and takes the result, so every function of type",
        "-- `A -> <E> C` it receives must run its effect when called, and every",
        "-- one it hands back must be seen by morloc as returning a suspension,",
        "-- whether the function arrives bare or inside a record, tuple, list,",
        "-- optional or map, and however that container was built.",
        "-- Report: /work/plans/host-adapter-by-type.md",
        "-- Generated by gen.py; do not edit by hand.",
        f"module main ({names})",
        "",
        f"import {IMPORT[lang]}",
    ]
    if lang in MAPMOD:
        lines.append(f"import {MAPMOD[lang]} (Map, fromList)")
    lines += [
        "",
        "record Ops where",
        "  get :: Int -> <IO> Int",
        "",
        "record Wrap where",
        "  inner :: Ops",
        "",
        f'record {src} => Ops = "{ops_t}"',
        f'record {src} => Wrap = "{wrap_t}"',
    ]
    host = [
        ("tick", "tick", "Str -> <IO> Int"),
        ("h_apply", "hApply", "(Int -> <IO> Int) -> Int -> <IO> Str"),
        ("h_ops", "hOps", "Ops -> Int -> <IO> Str"),
        ("h_wrap", "hWrap", "Wrap -> Int -> <IO> Str"),
        ("h_tup", "hTup", "(Int -> <IO> Int, Int) -> <IO> Str"),
        ("h_list", "hList", "[Int -> <IO> Int] -> Int -> <IO> Str"),
        ("h_opt", "hOpt", "?(Int -> <IO> Int) -> Int -> <IO> Str"),
        ("h_susp_ops", "hSuspOps", "<IO> Ops -> Int -> <IO> Str"),
        ("h_make_ops", "hMakeOps", "Int -> <IO> Ops"),
        ("h_make_list", "hMakeList", "Int -> <IO> [Int -> <IO> Int]"),
        ("h_cb_ret", "hCbRet", "(Int -> Ops) -> Int -> <IO> Str"),
        ("h_cb_param", "hCbParam", "(Ops -> <IO> Int) -> <IO> Str"),
    ]
    if lang in MAPMOD:
        host.append(("h_map", "hMap", "Map Str (Int -> <IO> Int) -> Int -> <IO> Str"))
    lines.append("")
    lines.append(f'source {src} from "{HOSTFILE[lang]}"')
    for i, (native, name, _) in enumerate(host):
        lead = "( " if i == 0 else ", "
        lines.append(f'  {lead}"{native}" as {name}')
    lines.append("  )")
    lines.append("")
    for _, name, sig in host:
        lines.append(f"{name} :: {sig}")
    lines += [
        "",
        "eff :: Str -> Int -> <IO> Int",
        "eff p i = do",
        "  n <- tick p",
        "  n * 100 + i",
        "",
        "ops :: Str -> Ops",
        f"ops p = {{ get = \\i -> eff p (i{PAD}) }}",
    ]
    for _, _, body, _ in shapes:
        lines.append(body)
    return "\n".join(lines) + "\n"


MIXED = """\
-- Effectful functions in a record built in one pool and handed to a host in
-- another: the record crosses as data and the host's pool adapts it.
-- Report: /work/plans/host-adapter-by-type.md
-- Generated by gen.py; do not edit by hand.
module main (pyToRust, rustToPy)

import root-py
import root-rust

record Ops where
  get :: Int -> <IO> Int

record Py => Ops = "dict"
record Rust => Ops = "Ops"

source Py from "host.py" ("tick" as tickPy, "h_ops" as hOpsPy)
source Rust from "host.rs" ("tick" as tickRs, "h_ops" as hOpsRs)

tickPy :: Str -> <IO> Int
hOpsPy :: Ops -> Int -> <IO> Str
tickRs :: Str -> <IO> Int
hOpsRs :: Ops -> Int -> <IO> Str

effPy :: Str -> Int -> <IO> Int
effPy p i = do
  n <- tickPy p
  n * 100 + i

effRs :: Str -> Int -> <IO> Int
effRs p i = do
  n <- tickRs p
  n * 100 + i

opsPy :: Str -> Ops
opsPy p = { get = \\i -> effPy p i }

opsRs :: Str -> Ops
opsRs p = { get = \\i -> effRs p i }

pyToRust :: Str -> <IO> Str
pyToRust p = hOpsRs (opsPy p) 5

rustToPy :: Str -> <IO> Str
rustToPy p = hOpsPy (opsRs p) 5
"""

MIXED_SHAPES = [("pyToRust", "ok 105"), ("rustToPy", "ok 105")]


def main():
    mk = ["all:", "\t: > obs.txt", "\trm -f *.err cnt-*"]
    exp = []

    def cells(prog, shapes):
        mk.append(f'\tmorloc make -o {prog} {prog}.loc 2>> build.err || echo "--- {prog} --- BUILD FAILED" >> obs.txt')
        for name, want in shapes:
            mk.append(f'\techo "--- {prog} {name} ---" >> obs.txt')
            mk.append(f"\t[ -x {prog} ] && ./{prog} {name} $$PWD/cnt-{prog}-{name} >> obs.txt 2>> obs.err || true")
            exp.append(f"--- {prog} {name} ---")
            exp.append(f'"{want}"' if want.startswith("ok") else want)

    for lang in LANGS:
        prog = f"main-{lang}"
        with open(f"{prog}.loc", "w") as f:
            f.write(program(lang))
        cells(prog, [(s[0], s[3]) for s in SHAPES if lang in s[1]])
    with open("main-mixed.loc", "w") as f:
        f.write(MIXED)
    cells("main-mixed", MIXED_SHAPES)
    progs = " ".join([f"main-{l}" for l in LANGS] + ["main-mixed"])
    mk += ["", "clean:", f"\trm -rf {progs} __pycache__ *.err cnt-*", "\trm -rf *-build *build.tmp*"]
    with open("Makefile", "w") as f:
        f.write("\n".join(mk) + "\n")
    with open("exp.txt", "w") as f:
        f.write("\n".join(exp) + "\n")


if __name__ == "__main__":
    main()
