#!/bin/sh
exec mim "$0" "$@"
### MANIFEST ###
{"version":1,"name":"test","build_dir":"/home/z/projects/morloc-core/morloc-workspace/compiler/morloc/test-suite/golden-tests/native-morloc-3","build_time":1771352633,"pools":[{"lang":"python3","exec":["python3","pools/pool.py"],"socket":"pipe-python3"}],"commands":[{"name":"foo","type":"remote","mid":1,"pool":0,"needed_pools":[0],"arg_schemas":["<list>a<int>i4"],"return_schema":"<list>a<int>i4","desc":[],"return_type":"[Int]","return_desc":[],"args":[]}]}