#!/bin/sh
exec mim "$0" "$@"
### MANIFEST ###
{"version":1,"name":"test","build_dir":"/home/z/projects/morloc-core/morloc-workspace/compiler/morloc/test-suite/golden-tests/native-morloc-2","build_time":1771352615,"pools":[{"lang":"python3","exec":["python3","pools/pool.py"],"socket":"pipe-python3"}],"commands":[{"name":"foo","type":"remote","mid":1,"pool":0,"needed_pools":[0],"arg_schemas":["<int>i4"],"return_schema":"<tuple>t2<int>i4<int>i4","desc":[],"return_type":"(Int, Int)","return_desc":[],"args":[{"kind":"pos","metavar":null,"type_desc":"Int","quoted":false,"desc":[]}]}]}