#!/usr/bin/env bash

loc -x tst x.loc &> /dev/null
./manifold-nexus.py map &> /dev/null
status=
if [[ -f tst/f-cars.pdf && -f tst/f-mtcars.pdf ]]
then
    status=0
else
    status=1
fi
rm -rf tst

exit $status
