#!/usr/bin/env bash
locstat=0
loc -x zzz x.loc            || locstat=1
./manifold-nexus.py min > a || locstat=1
./manifold-nexus.py max > b || locstat=1

diff a b &> /dev/null
stat=$?

rm -rf zzz manifold-nexus.py a b

exit $(( stat + locstat ))
