#!/usr/bin/env bash

loc -o tst x.loc &> /dev/null
tst/manifold-nexus.sh main &> /dev/null
status=
if [[ -f f-cars.pdf && -f f-iris.pdf && -f f-mtcars.pdf ]]
then
    status=0
else
    status=1
fi
rm -rf tst
rm *pdf

exit $status
