#!/usr/bin/env bash
cat <<EOF > z
[1,2,3]
1
2
3
[1, 2, 3]
EOF
stat=0
morloc -kx locout x.loc || stat=1
./manifold-nexus.py R   > y
./manifold-nexus.py sh >> y
./manifold-nexus.py py >> y
diff z y || stat=1
rm -rf locout z y manifold-nexus.py
exit $stat
