#!/bin/sh
exec mim "$0" "$@"
### MANIFEST ###
{"version":1,"build_time":1771049183,"pools":[{"lang":"python3","exec":["python3","/home/z/.local/share/morloc/exe/m-19257a0756b34bfc/pool.py"],"socket":"pipe-python3"}],"commands":[{"name":"foo","type":"remote","mid":1,"pool":0,"needed_pools":[0],"arg_schemas":["<int>i4","<int>i4"],"return_schema":"<int>i4","desc":[],"return_type":"Int","return_desc":[],"args":[{"kind":"pos","metavar":null,"type_desc":"Int","quoted":false,"desc":[]},{"kind":"pos","metavar":null,"type_desc":"Int","quoted":false,"desc":[]}]}]}