#!/usr/bin/env bash
cat << EOF > z
"na"
EOF

stat=0
loc -kx locout x.loc || stat=1
./manifold-nexus.py main > y 2> /dev/null
diff z y || stat=1
&> /dev/null
rm -rf locout z y manifold-nexus.py
exit $stat
