#!/usr/bin/env bash
locstat=0
loc -x zzz x.loc || locstat=1
./manifold-nexus.py tail > a || locstat=1
./manifold-nexus.py head > b || locstat=1

diff a b &> /dev/null
stat=$?

rm -rf zzz manifold-nexus.py a b

exit $(( stat + locstat ))
