#!/usr/bin/env bash
loc -x zzz x.loc
./manifold-nexus.py say_hi > a
./manifold-nexus.py say_bi > b
cat a b | diff /dev/stdin <(echo hi) &> /dev/null
stat=$?
rm -rf zzz manifold-nexus.py a b
exit $stat
