#!/usr/bin/env python3
"""Generate the per-language programs, Makefile and exp.txt of this golden.

Run from this directory after editing a shape: `python3 gen.py`.
"""

LANGS = ["py", "cpp", "rust", "r"]

IMPORT = {"py": "root-py", "cpp": "root-cpp", "rust": "root-rust", "r": "root-r"}
SOURCE = {"py": "Py", "cpp": "Cpp", "rust": "Rust", "r": "R"}
HOSTFILE = {"py": "host.py", "cpp": "host.hpp", "rust": "host.rs", "r": "host.R"}

# (name, definition, expected stdout); each prints how many times the effect
# ran, read from the counter file `p`
SHAPES = [
    ("mapUnforced", """
mapUnforced :: Str -> <IO> Int
mapUnforced p = do
  let ss = map (\\\\i -> eff p i) [1, 2, 3]
  count p""", "0"),
    ("mapForcedTwice", """
mapForcedTwice :: Str -> <IO> Int
mapForcedTwice p = do
  let ss = map (\\\\i -> eff p i) [1, 2, 3]
  a <- .[0] ss
  b <- .[2] ss
  count p""", "2"),
    ("passUnforced", """
passUnforced :: Str -> <IO> Int
passUnforced p = do
  let s = hPass (\\\\i -> eff p i) 1
  count p""", "0"),
    ("passForcedTwice", """
passForcedTwice :: Str -> <IO> Int
passForcedTwice p = do
  let s = hPass (\\\\i -> eff p i) 1
  a <- s
  b <- s
  count p""", "2"),
]


def program(lang):
    names = ", ".join(s[0] for s in SHAPES)
    src = SOURCE[lang]
    lines = [
        "-- A host whose parameter is a function of type variables (`map`,",
        "-- `a -> b`) instantiated at an effectful result: the host builds and",
        "-- returns suspensions, it does not run them. The effect runs only when",
        "-- the program forces a suspension, once per force.",
        "-- Report: /work/plans/host-adapter-by-type.md",
        "-- Generated by gen.py; do not edit by hand.",
        f"module main ({names})",
        "",
        f"import {IMPORT[lang]}",
        "",
        f'source {src} from "{HOSTFILE[lang]}" ("tick", "count", "h_pass" as hPass)',
        "",
        "tick :: Str -> <IO> Int",
        "count :: Str -> <IO> Int",
        "hPass :: (a -> b) -> a -> b",
        "",
        "eff :: Str -> Int -> <IO> Int",
        "eff p i = do",
        "  n <- tick p",
        "  n * 100 + i",
    ]
    for _, body, _ in SHAPES:
        lines.append(body.replace("\\\\", "\\"))
    return "\n".join(lines) + "\n"


def main():
    mk = ["all:", "\t: > obs.txt", "\trm -f *.err cnt-*"]
    exp = []
    for lang in LANGS:
        prog = f"main-{lang}"
        with open(f"{prog}.loc", "w") as f:
            f.write(program(lang))
        mk.append(f'\tmorloc make -o {prog} {prog}.loc 2>> build.err || echo "--- {prog} --- BUILD FAILED" >> obs.txt')
        for name, _, want in SHAPES:
            mk.append(f'\techo "--- {prog} {name} ---" >> obs.txt')
            mk.append(f"\t[ -x {prog} ] && ./{prog} {name} $$PWD/cnt-{prog}-{name} >> obs.txt 2>> obs.err || true")
            exp.append(f"--- {prog} {name} ---")
            exp.append(want)
    progs = " ".join(f"main-{l}" for l in LANGS)
    mk += ["", "clean:", f"\trm -rf {progs} __pycache__ *.err cnt-*", "\trm -rf *-build *build.tmp*"]
    with open("Makefile", "w") as f:
        f.write("\n".join(mk) + "\n")
    with open("exp.txt", "w") as f:
        f.write("\n".join(exp) + "\n")


if __name__ == "__main__":
    main()
