use std::fs;
use std::path::Path;
use std::process::{Command, Stdio};
use std::thread;
use std::time::Duration;

use crate::container::{
    container_build, container_pull, container_run, container_stop, container_remove,
    engine_executable, exit_code_to_int, BuildConfig, RunConfig,
};
use crate::error::{ManagerError, Result};
use crate::types::*;

pub fn build_serve_image(
    engine: ContainerEngine,
    state_tarball: &str,
    tag: &str,
    ver: Version,
    base_override: Option<&str>,
) -> Result<()> {
    if !Path::new(state_tarball).exists() {
        return Err(ManagerError::FreezeError(format!(
            "Tarball not found: {state_tarball}"
        )));
    }

    let tarball_dir = Path::new(state_tarball)
        .parent()
        .unwrap_or(Path::new("."));
    let manifest_path = tarball_dir.join("freeze-manifest.json");
    let m_manifest = if manifest_path.exists() {
        crate::freeze::read_freeze_manifest(&manifest_path.to_string_lossy()).ok()
    } else {
        None
    };

    let base_image = match base_override {
        Some(b) => b.to_string(),
        None => resolve_base_from_manifest(engine, m_manifest.as_ref(), ver),
    };

    eprintln!("Using base image: {base_image}");
    let (pull_status, _, pull_err) = container_pull(engine, &base_image);
    if !pull_status.success() {
        return Err(ManagerError::EngineError {
            engine,
            code: exit_code_to_int(pull_status),
            stderr: pull_err,
        });
    }

    let context_dir = tarball_dir.join("serve-build");
    fs::create_dir_all(&context_dir)
        .map_err(|e| ManagerError::FreezeError(format!("mkdir failed: {e}")))?;

    eprintln!("Extracting frozen state...");
    let tar_output = Command::new("tar")
        .args(["-xzf", state_tarball, "-C", &context_dir.to_string_lossy()])
        .output()
        .map_err(|e| ManagerError::FreezeError(format!("tar extract failed: {e}")))?;
    if !tar_output.status.success() {
        return Err(ManagerError::FreezeError(format!(
            "tar extract failed: {}",
            String::from_utf8_lossy(&tar_output.stderr)
        )));
    }

    let dockerfile_path = context_dir.join("Dockerfile");
    let dockerfile_content = format!(
        "# Auto-generated by morloc-manager serve-image\n\
         FROM {base_image}\n\
         \n\
         # Ensure morloc binaries are on PATH\n\
         ENV PATH=\"/opt/morloc/bin:${{PATH}}\"\n\
         \n\
         # Copy frozen morloc state (modules, manifests, binaries, pools)\n\
         COPY lib/ /opt/morloc/lib/\n\
         COPY fdb/ /opt/morloc/fdb/\n\
         COPY bin/ /opt/morloc/bin/\n\
         RUN chmod -R a+rX /opt/morloc\n\
         \n\
         # Health check for container orchestrators\n\
         HEALTHCHECK --interval=30s --timeout=5s --retries=3 \\\n\
           CMD wget -qO- http://localhost:8080/health || exit 1\n\
         \n\
         # Entrypoint: nexus router aggregates all installed programs\n\
         ENTRYPOINT [\"morloc-nexus\", \"--router\", \\\n\
                     \"--fdb\", \"/opt/morloc/fdb\"]\n"
    );
    fs::write(&dockerfile_path, &dockerfile_content)
        .map_err(|e| ManagerError::FreezeError(format!("Write Dockerfile failed: {e}")))?;

    eprintln!("Building serve image {tag} (base: {base_image})...");
    let build_cfg = BuildConfig {
        dockerfile: dockerfile_path.to_string_lossy().to_string(),
        context: context_dir.to_string_lossy().to_string(),
        tag: tag.to_string(),
        build_args: Vec::new(),
    };
    let (status, _, build_err) = container_build(engine, &build_cfg);
    if !status.success() {
        return Err(ManagerError::EngineError {
            engine,
            code: exit_code_to_int(status),
            stderr: build_err,
        });
    }
    eprintln!("Built serve image: {tag}");
    Ok(())
}

pub fn run_serve_container(
    engine: ContainerEngine,
    verbose: bool,
    image: &str,
    name: &str,
    ports: &[(u16, u16)],
) -> Result<()> {
    // Clean up any existing dead container with this name
    let _ = container_remove(engine, name);

    let port_str: Vec<String> = ports
        .iter()
        .map(|(h, c)| format!("{h}:{c}"))
        .collect();
    eprintln!(
        "Starting serve container {name} on ports {}...",
        port_str.join(", ")
    );

    let mut cfg = RunConfig::new(image);
    cfg.read_only = true;
    cfg.remove_after = false;
    cfg.name = Some(name.to_string());
    cfg.ports = ports.to_vec();
    cfg.extra_flags = vec!["-d".to_string()];

    if verbose {
        let exe = engine_executable(engine);
        let extra = crate::container::engine_specific_run_flags_io(engine);
        let args = crate::container::build_run_args(engine, &extra, &cfg);
        let quoted: Vec<String> = args.iter().map(|a| {
            if a.contains(' ') { format!("'{a}'") } else { a.clone() }
        }).collect();
        eprintln!("[morloc-manager] {exe} {}", quoted.join(" "));
    }

    let (status, _stdout, run_err) = container_run(engine, &cfg);
    if !status.success() {
        return Err(ManagerError::EngineError {
            engine,
            code: exit_code_to_int(status),
            stderr: run_err,
        });
    }

    // Verify container reached running state
    thread::sleep(Duration::from_secs(1));
    let exe = engine_executable(engine);
    let insp_output = Command::new(exe)
        .args(["inspect", "--format", "{{.State.Status}}", name])
        .output();
    match insp_output {
        Ok(o) if o.status.success() => {
            let state = String::from_utf8_lossy(&o.stdout).trim().to_string();
            if state == "running" {
                eprintln!("Container {name} started");
                Ok(())
            } else {
                let log_output = Command::new(exe).args(["logs", name]).output();
                let logs = log_output
                    .map(|o| {
                        let stdout = String::from_utf8_lossy(&o.stdout);
                        let stderr = String::from_utf8_lossy(&o.stderr);
                        format!("{stdout}{stderr}")
                    })
                    .unwrap_or_default();
                // Clean up the dead container to prevent name conflicts on retry
                let _ = container_remove(engine, name);
                Err(ManagerError::EngineError {
                    engine,
                    code: 1,
                    stderr: format!("Container failed to start (state: {state}):\n{logs}"),
                })
            }
        }
        _ => Err(ManagerError::EngineError {
            engine,
            code: 1,
            stderr: "Failed to inspect container state".to_string(),
        }),
    }
}

pub fn stop_serve_container(engine: ContainerEngine, name: &str) -> Result<()> {
    let (status, err) = container_stop(engine, name);
    let _ = container_remove(engine, name);
    if !status.success() {
        return Err(ManagerError::EngineError {
            engine,
            code: exit_code_to_int(status),
            stderr: err,
        });
    }
    Ok(())
}

pub fn list_serve_containers(engine: ContainerEngine) -> Result<()> {
    let exe = engine_executable(engine);
    let fmt = "{{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}";
    let output = Command::new(exe)
        .args([
            "ps", "-a", "--filter", "name=morloc-serve-", "--format", fmt,
        ])
        .output()
        .map_err(|e| ManagerError::EngineError {
            engine,
            code: 1,
            stderr: format!("Failed to list containers: {e}"),
        })?;
    if !output.status.success() {
        return Err(ManagerError::EngineError {
            engine,
            code: exit_code_to_int(output.status),
            stderr: String::from_utf8_lossy(&output.stderr).to_string(),
        });
    }
    let text = String::from_utf8_lossy(&output.stdout).trim().to_string();
    if text.is_empty() {
        println!("No morloc serve containers running.");
    } else {
        println!("NAME\tIMAGE\tSTATUS\tPORTS");
        print!("{text}");
    }
    Ok(())
}

pub fn stream_serve_logs(engine: ContainerEngine, name: &str, follow: bool) -> Result<()> {
    let exe = engine_executable(engine);
    let mut args = vec!["logs"];
    if follow {
        args.push("--follow");
    }
    args.push(name);

    let status = Command::new(exe)
        .args(&args)
        .stdin(Stdio::inherit())
        .stdout(Stdio::inherit())
        .stderr(Stdio::inherit())
        .status()
        .map_err(|e| ManagerError::EngineError {
            engine,
            code: 1,
            stderr: format!("Failed to stream logs: {e}"),
        })?;
    if status.success() {
        Ok(())
    } else {
        Err(ManagerError::EngineError {
            engine,
            code: exit_code_to_int(status),
            stderr: "Failed to read container logs".to_string(),
        })
    }
}

// ======================================================================
// Manifest and image resolution
// ======================================================================

fn resolve_base_from_manifest(
    engine: ContainerEngine,
    m_manifest: Option<&FreezeManifest>,
    ver: Version,
) -> String {
    let fallback = format!(
        "ghcr.io/morloc-project/morloc/morloc-full:{}",
        ver.show()
    );
    let Some(fm) = m_manifest else {
        return fallback;
    };
    match &fm.env_layer {
        None => fm.base_image.clone(),
        Some(fel) => {
            // Try using image digest (fast path)
            if let Some(ref digest) = fel.image_digest {
                let exe = engine_executable(engine);
                let check = Command::new(exe)
                    .args(["image", "inspect", digest])
                    .stdout(Stdio::null())
                    .stderr(Stdio::null())
                    .status();
                if check.map(|s| s.success()).unwrap_or(false) {
                    return digest.clone();
                }
            }
            rebuild_env_image(engine, fm, fel)
        }
    }
}

fn rebuild_env_image(
    engine: ContainerEngine,
    fm: &FreezeManifest,
    fel: &FrozenEnvLayer,
) -> String {
    let env_tag = format!(
        "localhost/morloc-env:{}-{}",
        fm.morloc_version.show(),
        fel.name
    );
    let exe = engine_executable(engine);
    // Check if tagged image exists locally
    let check = Command::new(exe)
        .args(["image", "inspect", &env_tag])
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status();
    if check.map(|s| s.success()).unwrap_or(false) {
        return env_tag;
    }

    eprintln!("Rebuilding environment: {}", fel.name);
    let build_dir = "/tmp/morloc-env-rebuild";
    let _ = fs::create_dir_all(build_dir);
    let df_path = format!("{build_dir}/Dockerfile");
    let _ = fs::write(&df_path, &fel.dockerfile);
    let build_cfg = BuildConfig {
        dockerfile: df_path,
        context: build_dir.to_string(),
        tag: env_tag.clone(),
        build_args: vec![("CONTAINER_BASE".to_string(), fm.base_image.clone())],
    };
    let (status, _, build_err) = container_build(engine, &build_cfg);
    if status.success() {
        env_tag
    } else {
        eprintln!(
            "Warning: env rebuild failed, falling back to base image: {build_err}"
        );
        fm.base_image.clone()
    }
}
